### ISSUE TITLE
No traces showed up

### ISSUE THREAD

**Issue by strelok29** [open-telemetry/opentelemetry-php-instrumentation#116]
**Describe your environment** 
We want to implement the Otel PHP auto instrumentation but are kinda stuck in the middle way. We are following this guide https://opentelemetry.io/docs/instrumentation/php/automatic/ and have installed the SDK and the Laravel auto instrumentation package. 
After we followed the guide, no traces appeared on our Jaeger instance. Just wondering if there is something that we missed or if we are doing something wrong. We have other instrumentation and it works fine.

We are using these stacks:
PHP Instrumentation 1.0.0
Laravel 10
PHP 8.1
PHP-FPM & NGINX
Kubernetes 1.26

Our config env:
OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.namespace.svc.cluster.local:4317 
OTEL_SERVICE_NAME=xyz
OTEL_PHP_AUTOLOAD_ENABLED=true 
OTEL_TRACES_EXPORTER=grpc 
OTEL_PROPAGATORS=baggage,tracecontext 
OTEL_EXPORTER_OTLP_PROTOCOL=grpc

**Steps to reproduce**
Follow this guide https://opentelemetry.io/docs/instrumentation/php/automatic/

**What is the expected behavior?**
Data shows up on our Jaeger instance

**What is the actual behavior?**
No data showed up, and no error founds

**Additional context**

**Comment by brettmc** [comment]
The first thing I'd try is to change the exporter to `console`. That should tell you if traces are being generated or not.
If you see traces in the console, then turn on logging in your collector - you should be able to see whether traces were received by the collector or not.

Other things to check:
- how do you set environment? It must be set _before_ you call the composer autoloader, and if you're using `artisan serve` then your environment is probably being lost.
- where are you checking for errors? By default they'll be logged via php's error_log, which could be to a file depending on your php config

**Comment by strelok29** [comment]
Thanks for your suggestion @brettmc , now I can see the log and find this error.

`2023/12/05 16:49:54 [error] 52#52: *368 FastCGI sent in stderr: "PHP message: PHP Warning:  The opentelemetry extension must be loaded in order to autoload the OpenTelemetry Laravel auto-instrumentation in /var/www/app/vendor/open-telemetry/opentelemetry-auto-laravel/_register.php on line 13" while reading response header from upstream, client: 10.0.64.80, server: _, request: "GET /health HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "10.0.66.58:80"`

do you know what might be the problem? I can see the `opentelemetry` module when I run `php -m` command

**Comment by brettmc** [comment]
fcgi might be using a different php.ini file (or ini dir) which doesn't have the extension registered. If you aren't sure where to look, I'd put a `phpinfo()` in your application and check the output there.
