### ISSUE TITLE
Will it support php7?

### ISSUE THREAD

**Issue by wilsondlli** [open-telemetry/opentelemetry-php-instrumentation#13]
Before opening a feature request against this repo, consider whether the feature should/could be implemented in the [other OpenTelemetry client libraries](https://github.com/open-telemetry). If so, please [open an issue in opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new) first.

**Is your feature request related to a problem?**
Many projects are using php7.

**Describe the solution you'd like**
[opentelemetry-php-instrumentation](https://github.com/open-telemetry/opentelemetry-php-instrumentation) support php7.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by bobstrecansky** [comment]
PHP 7.4 is running out of security support on 28 Nov 2022.  

We are attempting to align this project with currently supported versions of PHP.  

There are other features and functionality of this auto instrumentation that are also difficult to implement in PHP7.  If you'd like to support PHP 7.4, we could add it in our[ github action workflow](https://github.com/open-telemetry/opentelemetry-php-instrumentation/blob/main/.github/workflows/build.yml#L15), but the current roadmap does have us actively maintaining autoinstrumentation for PHP7.

**Comment by brettmc** [comment]
Hi @wilsondlli
Further to Bob's comments, auto-instrumentation is built around the observer API that was only added to PHP in 8.0, so it's not possible to work with earlier versions sorry.

**Comment by wilsondlli** [comment]
I see. Thanks for your reply.
