### ISSUE TITLE
OpenTelemetry\Instrumentation\hook not found

### ISSUE THREAD

**Issue by eliseuborges** [open-telemetry/opentelemetry-php-instrumentation#24]
Hi!

I am using lumen 9 with php 8.1 and after follow the installation process, the instruction "OpenTelemetry\Instrumentation\hook" still not available on my code.

**Steps to reproduce**
1. Install https://github.com/mlocati/docker-php-extension-installer and enable it.
2. Execute "install-php-extensions open-telemetry/opentelemetry-php-instrumentation@main"

**What is the expected behavior?**
I expected "OpenTelemetry\Instrumentation\hook" get no errors when it called by php

**What is the actual behavior?**
"OpenTelemetry\Instrumentation\hook" not found

**Comment by brettmc** [comment]
Hi @eliseuborges and welcome.
Firstly, can you verify whether the extension is installed via `php -m` or `php -i`/`phpinfo()` ? You should see `otel_instrumentation` listed.

**Comment by eliseuborges** [comment]
Hi @brettmc, 
After review my code I could see that "OpenTelemetry\Instrumentation\hook" instruction was without "\" (\OpenTelemetry\Instrumentation\hook) and after fix it, "not found" error wasn`t showed anymore.

Should I open a PR  add this small detail on example code at readme.md?

**Comment by brettmc** [comment]
> Should I open a PR add this small detail on example code at readme.md?

Yes please.
