### ISSUE TITLE
Laravel 9 auto instrumentation

### ISSUE THREAD

**Issue by petericebear** [open-telemetry/opentelemetry-php-instrumentation#30]
**Describe the solution you'd like**
Would be nice to let it autoinstrument Laravel 9 features like:
- Application boot / load time
- PDO Queries with timing
- Job invocations
- Loaded routes and triggered methods (detecting slow method calls)

**Comment by brettmc** [comment]
Hi @petericebear
I haven't heard of anybody looking at Laravel yet, but just wanted to point out that we have discussed auto-instrumenting PDO, and I think somebody has started some initial work on it. So, it might make sense to have PDO itself as a specialised library.

For anybody who wants to work on Laraval auto-instrumentation, help is available on our slack channel, `#otel-php-auto-instr` but we definitely don't have Laravel experience amongst the project maintainers.

**Comment by mikkeschiren** [comment]
The PDO instrumentation is now here https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Instrumentation/PDO

**Comment by brettmc** [comment]
Very basic (root span only) Laravel auto-instrumentation is here: https://github.com/brettmc/opentelemetry-php-contrib/tree/main/src/Instrumentation/Laravel
Also, https://github.com/plunkettscott/laravel-otel has been recently created which does manual instrumentation of Laravel.

**Comment by brettmc** [comment]
Closing as we have some Laravel auto-instrumentation now: https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/src/Instrumentation/Laravel
Please try it out :)
