### ISSUE TITLE
OpenTelemetry- Segfault with cache clear on Symfony 

### ISSUE THREAD

**Issue by tom-diacono** [open-telemetry/opentelemetry-php-instrumentation#60]
## My environment

I'm developing remotely on a K8S pod- though with the example repo I've posted below, I was able to re-create locally with docker aswell.

## The problem

I've installed Opentelemetry in a Symfony project that I'm working on. Initially, I was hitting an endpoint that I had in the project, which once every 5(ish) times caused a 502. I then checked the PHP logs, seeing the following error:

```
[07-Jun-2023 18:13:19] WARNING: [pool www] child 68 exited on signal 11 (SIGSEGV - core dumped) after 416.244705 seconds from start
```

I carried on playing around, this time in the terminal running a consumer workload (using the enqueue-php package to consume from Kafka). Again, I'd occasionally get a segfault:

```
Segmentation fault (core dumped)
```

After some more digging, I found that I could re-create the error each time by doing an `rm -rf var/cache/*` and then running a `composer install`. Which with the default Symfony config, will also run a `cache:clear` as well as a `assets:install`.\

## To reproduce:
I've created a [repository](https://github.com/tom-diacono/opentelemetry-bug) that contains the minimum I could to re-create the bug (I have added some tools like `strace` to the image aswell). Within the README there are some steps to reproduce, however for clarity:

1. Clone this repo
2. Run `sh build.sh`
3. Exec to the container `docker exec -it opentelem-bug /bin/bash`
4. Run `rm -rf var/cache/*`
5. Run `composer install`
6. See segfault

## What is the expected behavior?
I expect the `composer install` (and the scripts that it subsequently runs) to execute without a problem

 ## What is the actual behavior?
I see a seg fault

**Comment by tom-diacono** [comment]
Hi @brettmc, thanks for checking out the issue.

Is there any way you can point me to where it's moved to so I can monitor progress? Can't seem to find it in any of the other PHP repos.

Cheers :)

**Comment by pdelewski** [comment]
@tom-diacono You can monitor progress in this issue. Just to clarify, was issue originally opened in https://github.com/open-telemetry/opentelemetry-php?

**Comment by brettmc** [comment]
I still can't explain the segfault, however I took another look at this and I noticed that it was using very old versions of all of our packages (0.0.17). I changed minimum-stability to beta, updated otel dependencies to ^1 to get the latest beta versions of everything, and then the segfault went away.

@tom-diacono can you try that and verify?

**Comment by tom-diacono** [comment]
Hi @brettmc 

Thanks for taking the time to have a look. Seems there's good and bad news.

That seems to have fixed it to an extent.  So the good news is that for this repository, that did indeed fix it- however when I went to add the Symfony auto instrumentation to it, I was back to getting the seg-fault.

I've updated the [repository](https://github.com/tom-diacono/opentelemetry-bug) with [this commit](https://github.com/tom-diacono/opentelemetry-bug/commit/10635d8413efaff5d56721f2e396d107057038a9), containing updated versions, as well as extra Symfony package- where the same error can be witnessed.

I had previously been running a debugger on this and it was seg-faulting on a call to an `Enum::tryFrom` function- no idea if that's just coincidence or if there's something enum related (being a newer PHP feature) that it doesn't like.

**Comment by brettmc** [comment]
Hi @tom-diacono I finally got around to trying this out.
It fails to fail when I run it :(
```shell
docker exec -it opentelem-bug bash
root@3415298619ae:/home/opentelemetry-bug# rm -rf var/cache/*
root@3415298619ae:/home/opentelemetry-bug# bin/console c:c

 // Clearing the cache for the dev environment with debug true                                                          

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.
```

I checked out latest master, fixed volume mapping in `build+run.sh` then ran it, then exec etc as seen above. No other changes.
Do I need to do anything to populate the cache first?

**Comment by tom-diacono** [comment]
Hi @brettmc

Just checked and realised I'd not locked versioning down in `composer.json`. Ran a composer update (which bumped versions of a couple things) screenshot below:

```bash

root@a98a88312427:/home/opentelemetry-bug# rm -rf var/cache/*
root@a98a88312427:/home/opentelemetry-bug# bin/console c:c
Segmentation fault (core dumped)
root@a98a88312427:/home/opentelemetry-bug# composer install
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:884
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
34 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]

root@a98a88312427:/home/opentelemetry-bug# compser update
bash: compser: command not found
root@a98a88312427:/home/opentelemetry-bug# composer update
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:879
Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/bin/composer/src/Composer/Autoload/AutoloadGenerator.php:884
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Restricting packages listed in "symfony/symfony" to "6.2.*"
Updating dependencies
Lock file operations: 0 installs, 6 updates, 0 removals
  - Upgrading google/protobuf (v3.23.4 => v3.24.1)
  - Upgrading guzzlehttp/promises (2.0.0 => 2.0.1)
  - Upgrading open-telemetry/api (1.0.0beta11 => 1.0.0beta12)
  - Upgrading open-telemetry/exporter-otlp (1.0.0beta12 => 1.0.0beta13)
  - Upgrading open-telemetry/sdk (1.0.0beta15 => 1.0.0beta16)
  - Upgrading symfony/flex (v2.3.1 => v2.3.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 6 updates, 0 removals
  - Downloading symfony/flex (v2.3.3)
  - Downloading guzzlehttp/promises (2.0.1)
  - Downloading open-telemetry/api (1.0.0beta12)
  - Downloading open-telemetry/sdk (1.0.0beta16)
  - Downloading google/protobuf (v3.24.1)
  - Downloading open-telemetry/exporter-otlp (1.0.0beta13)
  - Upgrading symfony/flex (v2.3.1 => v2.3.3): Extracting archive
  - Upgrading guzzlehttp/promises (2.0.0 => 2.0.1): Extracting archive
  - Upgrading open-telemetry/api (1.0.0beta11 => 1.0.0beta12): Extracting archive
  - Upgrading open-telemetry/sdk (1.0.0beta15 => 1.0.0beta16): Extracting archive
  - Upgrading google/protobuf (v3.23.4 => v3.24.1): Extracting archive
  - Upgrading open-telemetry/exporter-otlp (1.0.0beta12 => 1.0.0beta13): Extracting archive
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
34 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]

root@a98a88312427:/home/opentelemetry-bug# rm -rf var/cache/*
root@a98a88312427:/home/opentelemetry-bug# bin/console c:c

 // Clearing the cache for the dev environment with debug true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


root@a98a88312427:/home/opentelemetry-bug# rm -rf var/cache/*
root@a98a88312427:/home/opentelemetry-bug# bin/console c:c

```

So want to say it's fixed. Will have a hack around in my work repo and see if it's now working in there also or if I can re-create a similar issue. Looks to me like some other bugfix has sorted this however!
