### ISSUE TITLE
I cant use hook function 

### ISSUE THREAD

**Issue by GrayWolfy** [open-telemetry/opentelemetry-php-instrumentation#61]
Here are my Dockerfile lines:

```
# Install php-extension-installer
RUN curl -o /usr/local/bin/install-php-extensions https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions && \
    chmod +x /usr/local/bin/install-php-extensions

# Install OpenTelemetry extension
RUN install-php-extensions open-telemetry/opentelemetry-php-instrumentation@main

# Install gRPC extension
RUN install-php-extensions grpc

# Confirm the extensions are installed
RUN php -m | grep opentelemetry
RUN php -m | grep grpc

# Set OpenTelemetry environment variables for automatic instrumentation
ENV OTEL_PHP_AUTOLOAD_ENABLED=true
ENV OTEL_SERVICE_NAME=auth
ENV OTEL_TRACES_EXPORTER=otlp
ENV OTEL_EXPORTER_OTLP_PROTOCOL=grpc
ENV OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
ENV OTEL_PROPAGATORS=baggage,tracecontext

```

Seems that everything is set.

here is my composer json:
```

{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": [
        "yii2",
        "framework",
        "basic",
        "project template"
    ],
    "homepage": "https://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "https://www.yiiframework.com/forum/",
        "wiki": "https://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=8.1",
        "yiisoft/yii2": "~2.0.10",
        "yiisoft/yii2-bootstrap5": "~2.0.2",
        "yiisoft/yii2-symfonymailer": "~2.0.3",
        "guzzlehttp/guzzle": "^7.5",
        "firebase/php-jwt": "^6.4",
        "ramsey/uuid": "^4.7",
        "borales/yii2-phone-input": "^0.3.0",
        "vlucas/phpdotenv": "^5.5",
        "zircote/swagger-php": "^4.7",
        "light/yii2-swagger": "^3.0",
        "codeception/module-rest": "^1.2",
        "yiisoft/yii2-redis": "^2.0",
        "codemix/yii2-streamlog": "^1.3",
        "open-telemetry/api": "^0.0.17",
        "open-telemetry/context": "^0.0.17",
        "open-telemetry/sdk": "^0.0.17",
        "php-http/guzzle7-adapter": "^1.0",
        "open-telemetry/exporter-otlp": "^0.0.17",
        "open-telemetry/gen-otlp-protobuf": "^0.0.17",
        "open-telemetry/sem-conv": "^0.0.17",
        "open-telemetry/transport-grpc": "^0.0.17",
        "open-telemetry/opentelemetry-instrumentation-installer": "^0.0.4"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.1.0",
        "yiisoft/yii2-gii": "~2.2.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "phpunit/phpunit": "~9.5.0",
        "codeception/verify": "^2.2",
        "symfony/browser-kit": "^5.4",
        "guzzlehttp/guzzle-services": "^1.3",
        "codeception/aspect-mock": "^3.0",
        "codeception/codeception": "^4.2",
        "codeception/module-phpbrowser": "^1.0",
        "codeception/module-rest": "^1.2",
        "codeception/lib-innerbrowser": "^1.5",
        "codeception/module-asserts": "^1.3",
        "codeception/module-yii2": "^1.1",
        "codeception/module-filesystem": "^2.0",
        "infection/codeception-adapter": "^0.4.1",
        "infection/infection": "*"
    },
    "config": {
        "allow-plugins": {
            "yiisoft/yii2-composer": true,
            "php-http/discovery": true,
            "infection/extension-installer": true
        },
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "scripts": {
        "post-install-cmd": [
            "yii\\composer\\Installer::postInstall"
        ],
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ]
        },
        "yii\\composer\\Installer::postInstall": {
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}

```
every dependency is set.

but when i enter ur example lines:

```php
OpenTelemetry\Instrumentation\hook(
    DemoClass::class,
    'run',
    static function (DemoClass $demo, array $params, string $class, string $function, ?string $filename, ?int $lineno) use ($tracer) {
        $span = $tracer->spanBuilder($class)
            ->startSpan();
        Context::storage()->attach($span->storeInContext(Context::getCurrent()));
    },
    static function (DemoClass $demo, array $params, $returnValue, ?Throwable $exception) use ($tracer) {
        $scope = Context::storage()->scope();
        $scope?->detach();
        $span = Span::fromContext($scope->context());
        $exception && $span->recordException($exception);
        $span->setStatus($exception ? StatusCode::STATUS_ERROR : StatusCode::STATUS_OK);
        $span->end();
    }
);
```

There is no such namespace OpenTelemetry\Instrumentation\ it's wether OpenTelemetry\API\Common\Instrumentation\ or OpenTelemetry\SDK\Common\Instrumentation\

And there is no sign of such hook func.

installation via open-telemetry/opentelemetry-instrumentation-installer in container requires write rights inside container.
So it's a bit complicated.

Is there an easy way to autoinstrument an app? Because I'm dying trying.

**Comment by brettmc** [comment]
`OpenTelemetry\Instrumentation\hook` function is provided by the extension, so it should be available if you have installed and enabled the extension: https://github.com/open-telemetry/opentelemetry-php-instrumentation/blob/main/opentelemetry.stub.php

Your IDE is probably unaware of it, though, if that's how you are trying to locate it?

**Comment by GrayWolfy** [comment]
> `OpenTelemetry\Instrumentation\hook` function is provided by the extension, so it should be available if you have installed and enabled the extension: https://github.com/open-telemetry/opentelemetry-php-instrumentation/blob/main/opentelemetry.stub.php
> 
> Your IDE is probably unaware of it, though, if that's how you are trying to locate it?
> 
> > "open-telemetry/api": "^0.0.17"
> 
> These versions are quite old, we are deep into beta now. You should set your minimum stability in composer.json to `beta` or lower, or explicitly require beta versions.

Yep u are right, my IDE doesn't see it, and i required beta explicitly for every opentelemetry package.
But can u help me? I've made autoinstrumentation exactly as in example.

```
OpenTelemetry\Instrumentation\hook(
    yii\web\Application::class,
    'run',
    static function (yii\web\Application $demo, array $params, string $class) {
    static $instrumentation;
    $instrumentation ??= new CachedInstrumentation('example');
    $span = $instrumentation->tracer()->spanBuilder($class)->startSpan();
    Context::storage()->attach($span->storeInContext(Context::getCurrent()));
},
    static function (yii\web\Application $demo, array $params, $returnValue, ?Throwable $exception) {
    $scope = Context::storage()->scope();
    $scope->detach();
    $span = Span::fromContext($scope->context());
    if ($exception) {
        $span->recordException($exception);
        $span->setStatus(StatusCode::STATUS_ERROR);
    }
    $span->end();
}
);
//$span = Globals::tracerProvider()
//    ->getTracer('manual-instrumentation')
//    ->spanBuilder('calculate-quote')
//    ->setSpanKind(SpanKind::KIND_CLIENT)
//    ->startSpan();


$demo = new yii\web\Application($config);
$demo->run();
//$span->end();
```


envs set:

```
# Set OpenTelemetry environment variables for automatic instrumentation
ENV OTEL_PHP_AUTOLOAD_ENABLED=true
ENV OTEL_SERVICE_NAME=auth
ENV OTEL_TRACES_EXPORTER=otlp
ENV OTEL_EXPORTER_OTLP_PROTOCOL=grpc
ENV OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
ENV OTEL_PROPAGATORS=baggage,tracecontext
```

See nothing in jaeger. Can u point me?

**Comment by brettmc** [comment]
Your code looks pretty good to me, it must be very close to working.

A couple of things to try and report back on:
- add a var_dump or other output to your pre/post functions, to make sure they are running
- add a psr3 logger (see https://opentelemetry.io/docs/instrumentation/php/manual/#logging-and-error-handling ) and see if it gives you any extra info
- also var_dump `$instrumentation->tracer()` to make sure it's not a no-op (which will happen if there was some misconfiguration...but logs should show that)

**Comment by GrayWolfy** [comment]
> Your code looks pretty good to me, it must be very close to working.
> 
> A couple of things to try and report back on:
> 
> * add a var_dump or other output to your pre/post functions, to make sure they are running
> * add a psr3 logger (see https://opentelemetry.io/docs/instrumentation/php/manual/#logging-and-error-handling ) and see if it gives you any extra info
> * also var_dump `$instrumentation->tracer()` to make sure it's not a no-op (which will happen if there was some misconfiguration...but logs should show that)

Nothing happen as if those functions weren't called.

![image](https://github.com/open-telemetry/opentelemetry-php-instrumentation/assets/28788053/c089e81a-5fdc-4cce-bd34-3c35292263ea)

![image](https://github.com/open-telemetry/opentelemetry-php-instrumentation/assets/28788053/5202ce39-a19e-40fa-82da-519e302a26c9)

**Comment by GrayWolfy** [comment]
Update. For some reason run method isn't hooked, if i call other yii/web/Applications functions and hook them instead they are hooked alright

**Comment by GrayWolfy** [comment]
Update

> Your code looks pretty good to me, it must be very close to working.
> 
> A couple of things to try and report back on:
> 
> * add a var_dump or other output to your pre/post functions, to make sure they are running
> * add a psr3 logger (see https://opentelemetry.io/docs/instrumentation/php/manual/#logging-and-error-handling ) and see if it gives you any extra info
> * also var_dump `$instrumentation->tracer()` to make sure it's not a no-op (which will happen if there was some misconfiguration...but logs should show that)

Update, sry Brett, I've noticed that yii/web/Application extends yii/base/Application, and run is called outta there. So I just needed to replace class name.

One more question. I still get this warning, how to fix this?
And Now I see it in jaeger like this:

![image](https://github.com/open-telemetry/opentelemetry-php-instrumentation/assets/28788053/66cfef13-5034-4137-98c2-c62b61024d5f)

I don't see any inner calls: controllers, methods and responses sent and etc. Should I? Or there is a need to do some spans inside controllers?

**Comment by brettmc** [comment]
> One more question. I still get this warning

https://github.com/opentelemetry-php/sdk/releases/tag/1.0.0beta9 is where `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` was introduced, can you check that you have this version or later?

> I don't see any inner calls: controllers, methods and responses sent and etc. Should I? Or there is a need to do some spans inside controllers?

You need to install an [auto-instrumentation package](https://opentelemetry.io/docs/instrumentation/php/automatic/#supported-libraries-and-frameworks) that knows about `yii` (we don't have one specifically, but if it implements some of the PSR interfaces, we do have packages for those). Alternatively, write hook functions for controllers etc as you have done for the `run` method.
Lastly, yes you can do manual instrumentation inside your code (eg in controllers), it's fine to mix auto and manual instrumentation.

**Comment by GrayWolfy** [comment]
> https://github.com/opentelemetry-php/sdk/releases/tag/1.0.0beta9 is where `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` was introduced, can you check that you have this version or later?

```
  - Upgrading open-telemetry/sdk (1.0.0beta8 => 1.0.0beta9)
  - Downgrading psr/http-message (2.0 => 1.1)
```
It downgraded my psr/http-message is it ok btw? 'Cause seems itchy. After that I started to receive this:

[error] Export failure,  'cause of "unknown service opentelemetry.proto.collector.metrics.v1.MetricsService"

Do u know how to fix that?

**Comment by brettmc** [comment]
> Downgrading psr/http-message (2.0 => 1.1)

I wasn't aware that v2 had come out. It looks like it just adds type hints, I can create a PR to allow this version. I don't think it's related to the error you see.

> unknown service opentelemetry.proto.collector.metrics.v1.MetricsService

I think that's an error response from the service you are trying to send telemetry to (via `gRPC`?) Actually, that makes sense if I think about it, you're using jaeger, but that only accepts traces. So, you should turn off metrics: `OTEL_METRICS_EXPORTER=none`

**Comment by GrayWolfy** [comment]
> I think that's an error response from the service you are trying to send telemetry to (via `gRPC`?) Actually, that makes sense if I think about it, you're using jaeger, but that only accepts traces. So, you should turn off metrics: `OTEL_METRICS_EXPORTER=none`

Yep that worked. Thank you very much!:)

**Comment by GrayWolfy** [comment]
> I wasn't aware that v2 had come out. It looks like it just adds type hints, I can create a PR to allow this version. I don't think it's related to the error you see.

Yeah, this doesn't affect anything, it seems. But better keep up, I presume.
