### ISSUE TITLE
The path '/tmp/opentelemetry-php-instrumentation' doesn't contain package.xml

### ISSUE THREAD

**Issue by lhintzsc** [open-telemetry/opentelemetry-php-instrumentation#67]
**Describe your environment**

Base Docker Image: 
* php:8-fpm-bullseye

PHP Version: 
* PHP 8.2.7 (cli) (built: Jun 13 2023 23:25:14) (NTS)

Composer version:
* 2.5.8 2023-06-09 17:13:21

GCC version: 
* gcc (Debian 10.2.1-6) 10.2.1 20210110

Clang version:
* Debian clang version 11.0.1-2, Target: aarch64-unknown-linux-gnu

**Steps to reproduce**
* I follow the installation guideline: https://opentelemetry.io/blog/2023/php-auto-instrumentation/
* composer require open-telemetry/opentelemetry-instrumentation-installer (OK)
* ./vendor/bin/install-otel-instrumentation basic (NOK)

=> Error message:

./vendor/bin/install-otel-instrumentation basic
php pickle.phar install --source https://github.com/open-telemetry/opentelemetry-php-instrumentation.git#main  -n 
  - Installing opentelemetry-php-instrumentation (main): Cloning main from cache 
 
In PackageXml.php line 68: 
 
  The path '/tmp/opentelemetry-php-instrumentation' doesn't contain package.xml 
 
install [--no-convert] [--defaults] [--source] [--with-configure-options WITH-CONFIGURE-OPTIONS] [--save-logs SAVE-LOGS] [--dry-run] [--php PHP] [--ini INI] [--tmp-dir TMP-DIR] [--version-override [VERSION-OVERRIDE]] [--] [<path>] 

**What is the expected behavior?**

* ./vendor/bin/install-otel-instrumentation basic runs through and I can proceed with the guide: https://opentelemetry.io/blog/2023/php-auto-instrumentation/

**What is the actual behavior?**
I am blocked during the installation steps

**Comment by lhintzsc** [comment]
I compared the main with beta6. The package.xml moved from the main folder to a sub-folder. As a result, the installer will work only for the beta6 version or the main. I see following options: (a) the package.xml goes back in main (b) dependent installation scripts must have the option to pass the version as an argument. Lets see. Maybe I can fix it an propose the solution here.

**Comment by lhintzsc** [comment]
Following https://opentelemetry.io/blog/2023/php-auto-instrumentation/:

* step "./vendor/bin/install-otel-instrumentation basic" must be changed to "./vendor/bin/install-otel-instrumentation basic version"
* in /script/vendor/open-telemetry/opentelemetry-instrumentation-installer/install-otel-instrumentation, line 11
should return not only the mode from the arguments but also the version, or the version is passed as package reference

* in /script/vendor/open-telemetry/opentelemetry-instrumentation-installer/installer_internals.php, line 393
instead of hard-coding main, the version number must be parsed

Now, I go into the WE. However, I can fix the issue locally on Monday. Just let me know if I you can include the fix in your your code or another OTel project. Cheers

**Comment by brettmc** [comment]
I haven't worked on the installer before, but this looks like a problem since we moved the code into a directory:

> php pickle.phar install --source https://github.com/open-telemetry/opentelemetry-php-instrumentation.git#main -n

AFAIK pickle can not install from github with a subdirectory, so we should probably update the installer to use pecl. The installer pre-dates our project getting pecl access, which is why it currently installs from source. As we get closer to a GA release, I don't think there is a strong case for installing `main`.

So, I think the fix is to update the installer. I don't think there's a way with pecl to specify "stable or beta", but if somebody can find a way to get it to install the best available of beta|rc|stable that should work for future versions.

**Comment by lhintzsc** [comment]
I used the following workaround so far (in in /script/vendor/open-telemetry/opentelemetry-instrumentation-installer/installer_internals.php):

* replaced the hard-coded main with hard-coded the tag:

function make_basic_setup($dependencies, $core_packages, $auto_packages) {
  execute_command(make_pickle_install(
    "https://github.com/open-telemetry/opentelemetry-php-instrumentation.git",
    "#1.0.0beta6", " -n"), " 2>&1");
  update_ini_file(get_php_info_output());

* Then I ran into another problem when the composer tried to install the detected auto instrumentation packages. As a result, I limited the search to only the needed package in my case:

function get_auto_packages(): array {
  colorLog ("get_auto_packages\n", 'e');
  $auto_packages = "https://packagist.org/search.json?q=opentelemetry-auto";
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $auto_packages);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
  $output = curl_exec($ch);
  curl_close($ch);
  $json = json_decode($output);
  $results = $json->{"results"};
  $opentelemetry_auto_packages = array();
  foreach ($results as $package) {
    array_push($opentelemetry_auto_packages, $package->name);
  }
  $opentelemetry_auto_packages = array();
  array_push($opentelemetry_auto_packages, "open-telemetry/opentelemetry-auto-slim");
  return $opentelemetry_auto_packages;
}
  
 Lessons learned so far:
 * in the installer it is not so good to reference the hard-coded main branch. Better to reference a specific, fixed artifact for a specific realease version
 * it is not so good to capture the auto detection packages automatically from the repo. It might be better to move this to a config file

I continue with the hard-coded workaround for the moment.

**Comment by lhintzsc** [comment]
Problem solved:
* I used the pickle to install the package artifact for a specific version
* I followed the instructions on github for the tag: https://github.com/open-telemetry/opentelemetry-php-instrumentation/tree/1.0.0beta6

Here the docker RUNs:

RUN composer require \
    slim/slim:"^4" \
    slim/psr7:"^1" \
    php-http/guzzle7-adapter:"1.0.0" \
    grpc/grpc:"^1.38" \
    open-telemetry/sdk:"1.0.0beta13" \
    open-telemetry/opentelemetry:"1.0.0beta1" \
    open-telemetry/exporter-otlp:"1.0.0beta11"

RUN pecl install \
    opentelemetry-1.0.0beta6 \
    protobuf-3.23.3 

RUN echo "[opentelemetry]" >> /usr/local/etc/php/conf.d/docker-fpm.ini && \
    echo "extension=opentelemetry.so" >> /usr/local/etc/php/conf.d/docker-fpm.ini && \
    echo "extension=protobuf.so" >> /usr/local/etc/php/conf.d/docker-fpm.ini

RUN wget https://github.com/FriendsOfPHP/pickle/releases/tag/v0.7.11/pickle.phar && \
    php pickle.phar install --source https://github.com/open-telemetry/opentelemetry-php-instrumentation.git#1.0.0beta6

**Comment by brettmc** [comment]
@lhintzsc this should be fixed now in installer v0.0.5
